create TABLE IF NOT EXISTS task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title       VARCHAR(100)                            NOT NULL,
    description TEXT,
    completed   BOOLEAN DEFAULT FALSE,
);

CREATE INDEX IF NOT EXISTS idx_task_completed ON task(completed);