create TABLE IF NOT EXISTS "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(50)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

alter table "user"
    add CONSTRAINT uc_user_email UNIQUE (email);

alter table "user"
    add CONSTRAINT uc_user_username UNIQUE (username);